#!/bin/bash

filename=$(basename "$1")
filename="${1%.*}"
directory="$filename.iconset"
echo 
mkdir "$directory"

convert "$1" -resize 1024x1024 "$directory/icon_512x512@2x.png"

convert "$1" -resize 512x512 "$directory/icon_512x512.png"
convert "$1" -resize 512x512 "$directory/icon_256x256@2x.png"

convert "$1" -resize 256x256 "$directory/icon_256x256.png"
convert "$1" -resize 256x256 "$directory/icon_128x128@2x.png"

convert "$1" -resize 128x128 "$directory/icon_128x128.png"

convert "$1" -resize 64x64 "$directory/icon_32x32@2x.png"

convert "$1" -resize 32x32 "$directory/icon_32x32.png"
convert "$1" -resize 32x32 "$directory/icon_16x16@2x.png"

convert "$1" -resize 16x16 "$directory/icon_16x16.png"

echo "DONE!"